spring:
  application:
    name: 'router-service'
  cloud:
    gateway:
      routes:
        - id: index
          uri: http://host.docker.internal:8085/index.html
          predicates:
            - Path=/
        - id: frontend-service
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/index.html,/built/**
        - id: bet
          uri: http://main-service:8080
          predicates:
            - Path=/bet/**
        - id: chatpost
          uri: http://main-service:8080
          predicates:
            - Path=/chat_post/**
        - id: game
          uri: http://main-service:8080
          predicates:
            - Path=/game/**
        - id: price
          uri: http://main-service:8080
          predicates:
            - Path=/price/**
        - id: auth
          uri: http://user-service:8080
          predicates:
            - Path=/auth/**
        - id: customer
          uri: http://user-service:8080
          predicates:
            - Path=/customer/**
        - id: ws
          uri: http://websocket-service:8080
          predicates:
            - Path=/ws/**
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans