global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'router-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'router-service:8080'
  - job_name: 'frontend-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'frontend-service:8080'
  - job_name: 'audit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'audit-service:8080'
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'user-service:8080'
  - job_name: 'main-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'main-service:8080'
  - job_name: 'websocket-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'websocket-service:8080'
  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'