spring:
  application:
    name: "user-service"
  main:
    web-application-type: reactive
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling.probability: 0.05
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans