spring:
  application:
    name: "user-service"
  main:
    web-application-type: reactive
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5434/postgres'
    username: postgres
    password: postgres
app:
  auth:
    token: 1236235613479587132984569812379867192387698172896739814643673471734
    expiration-minutes: 600
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans