apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-statefulset
spec:
  serviceName: kafka-service
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:7.4.4
          ports:
            - containerPort: 9090
            - containerPort: 9091
          volumeMounts:
            - name: kafka-volume
              mountPath: /var/lib/kafka
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "kafka-zookeeper-service:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT_INTER:PLAINTEXT,PLAINTEXT_HOST1:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT_INTER://kafka-service:9090,PLAINTEXT_HOST1://kafka-service:9091"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT_INTER"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          readinessProbe:
            tcpSocket:
              port: 9091
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 30
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "sh /bin/kafka-broker-api-versions --bootstrap-server=localhost:9091"
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: kafka-volume
      spec:
        storageClassName: kafka-volume-class
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-volume
spec:
  storageClassName: kafka-volume-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/bettingplatform/kafka"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - port: 9090
      name: port0
    - port: 9091
      name: port1