apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-zookeeper-statefulset
spec:
  serviceName: kafka-zookeeper-service
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: kafka-zookeeper
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - name: kafka-zookeeper-container
          image: confluentinc/cp-zookeeper:7.4.4
          ports:
            - containerPort: 2181
              name: http
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 15
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 15
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper-service
  labels:
    app: kafka-zookeeper
spec:
  type: NodePort
  selector:
    app: kafka-zookeeper
  ports:
    - name: port0
      port: 2181