apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: main-service-postgres-deployment
spec:
  serviceName: main-service-postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: main-service-postgres
  template:
    metadata:
      labels:
        app: main-service-postgres
    spec:
      containers:
        - name: main-service-postgres-container
          image: 'postgres:14'
          resources:
            limits:
              memory: "1G"
              cpu: "1"
            requests:
              memory: "1G"
              cpu: "1"
          envFrom:
            - secretRef:
                name: main-service-postgres-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: main-service-postgres-container-vol
              mountPath: /var/lib/postgresql/data
            - name: main-service-postgres-configmap-init-vol
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: main-service-postgres-configmap-init-vol
          configMap:
            name: main-service-postgres-configmap-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: main-service-postgres-service
spec:
  type: NodePort
  selector:
    app: main-service-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: main-service-postgres-container-vol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/main_service_postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: main-service-postgres-configmap-init
data:
  01_init_db.sql: |-
    CREATE TABLE IF NOT EXISTS users
    (
        id         bigserial PRIMARY KEY,
        username   character varying(1000) NOT NULL,
        password   character varying(1000) NOT NULL,
        first_name character varying(1000) NOT NULL,
        last_name  character varying(1000) NOT NULL,
        email      character varying(1000),
        phone      character varying(1000)
    );