apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-statefulset
spec:
  serviceName: prometheus-service
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      initContainers:
        - name: chown
          image: busybox:1.28
          command: [ 'chown', '-R', '65534:root', '/prometheus' ]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: prometheus-volume
              mountPath: /prometheus
      containers:
        - name: prometheus-container
          image: prom/prometheus:v2.53.0
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: prometheus-volume
              mountPath: /prometheus
          readinessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 15
  volumeClaimTemplates:
    - metadata:
        name: prometheus-volume
      spec:
        storageClassName: prometheus-volume-class
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-volume
spec:
  storageClassName: prometheus-volume-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/bettingplatform/prometheus"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: web