apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-statefulset
spec:
  serviceName: prometheus-service
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus-container
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
          ports:
            - containerPort: 9200
              name: http
          volumeMounts:
            - name: prometheus-volume
              mountPath: /prometheus
  volumeClaimTemplates:
    - metadata:
        name: prometheus-volume
      spec:
        storageClassName: prometheus-volume-class
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-volume
spec:
  storageClassName: prometheus-volume-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/bettingplatform/prometheus"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: web