apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
spec:
  serviceName: rabbitmq-service
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3.13.1-management-alpine
          ports:
            - containerPort: 5672
              name: port0
            - containerPort: 61613
              name: port1
          readinessProbe:
            exec:
              command:
                - "rabbitmq-diagnostics"
                - "-q"
                - "ping"
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 15
          livenessProbe:
            exec:
              command:
                - "rabbitmq-diagnostics"
                - "-q"
                - "ping"
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 15
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rabbitmq
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-config
            items:
              - key: enabled_plugins
                path: enabled_plugins
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-volume
      spec:
        storageClassName: rabbitmq-volume-class
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: "[rabbitmq_management,rabbitmq_stomp]."
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-volume
spec:
  storageClassName: rabbitmq-volume-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/bettingplatform/rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: port0
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: port1
      protocol: TCP
      port: 61613
      targetPort: 61613
