apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-service-deployment
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: router-service
  template:
    metadata:
      labels:
        app: router-service
    spec:
      containers:
        - name: router-service-container
          image: slow3586/betting-platform:router-service-0.0.1
          imagePullPolicy: Always
          env:
            - name: management.zipkin.tracing.endpoint
              value: http://zipkin:9411/api/v2/spans
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: router-service-service
  labels:
    app: router-service
spec:
  type: NodePort
  selector:
    app: router-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: router-service-monitor
spec:
  selector:
    matchLabels:
      app: router-service
  endpoints:
    - interval: 15s
      port: web
      path: /actuator/prometheus
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: changeme.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router-service-service
                port:
                  number: 8080