spring:
  application:
    name: 'websocket-service'
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  jackson:
    default-property-inclusion: non_absent

app:
  client:
    main: 'localhost:8082'
    user: 'localhost:8083'

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans