spring:
  application:
    name: 'websocket-service'
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

app:
  websocket:
    kafka-broker: 'localhost:9091'
  client:
    bet: 'localhost:8082'
    user: 'localhost:8083'

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true