spring:
  application:
    name: "frontend-service"
  devtools:
    livereload:
      enabled: true
  web:
    resources:
      static-locations:
        - 'file:src/main/resources/static/'
        - 'classpath:/static/'
  codec:
    max-in-memory-size: 50MB
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true