spring:
  application:
    name: 'bettingservice'

app:
  price:
    request-path: 'https://api.binance.com/api/v3/uiKlines?symbol=BNBUSDT&interval=1s&limit=1'
    request-date-format: 'yyyy-MM-dd\\THH:mm'
    response-regex: '"entries":\\[\\[.*?,(.*?)\\]\\]'
    request-instrument: 'BTC'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true